on:
  push:
    branches:
      - main
jobs:
  TEST:
    runs-on:
      ubuntu-latest
    env:
      VAULT_ADDR: http://mgmt.ndne.co.kr:8200
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Vault get AWS Keys
        id: aws_creds
        run: |
          curl -o ./aws_data.json \
          --header "X-Vault-Token: ${{ env.VAULT_TOKEN }}" \
          ${{ env.VAULT_ADDR }}/v1/aws-terraform-dev/creds/local-execute
          
      - name: Store AWS data
        id: aws_store
        run: |
          echo "ACCESS_KEY=`cat aws_data.json | jq -r '.data.access_key'`" >> $GITHUB_OUTPUT
          echo "SECRET_KEY=`cat aws_data.json | jq -r '.data.secret_key'`" >> $GITHUB_OUTPUT
          echo "LEASE_ID=`cat aws_data.json | jq -r '.lease_id'`" >> $GITHUB_ENV
          
      - name: Show AWS data
        id: aws_data
        run: |
          echo ${{ steps.aws_store.outputs.ACCESS_KEY }}
          echo ${{ env.LEASE_ID }}
          sleep 10
          
      - name: Vault revoke AWS Keys
        run: |
          curl \
          --header "X-Vault-Token: ${{ env.VAULT_TOKEN }}" \
          --data '{"lease_id": "${{ env.LEASE_ID }}"}' \
          ${{ env.VAULT_ADDR }}/v1/sys/leases/revoke
