on:
  push:
    branches:
      - main
jobs:
  TEST:
    runs-on:
      ubuntu-latest
    env:
      VAULT_ADDR: http://mgmt.ndne.co.kr:8200
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Vault get AWS Keys
        id: aws_creds
        run: |
          curl -o ./aws_data.json \
          --header "X-Vault-Token: ${{ env.VAULT_TOKEN }}" \
          ${{ env.VAULT_ADDR }}/v1/aws-terraform-dev/creds/local-execute
          
      - name: Vault revoke AWS Keys
        run: |
          sudo apt-get install -y jq
          lease_id=`cat aws_data.json | jq -r '.lease_id'`
          curl \
          --header "X-Vault-Token: ${{ env.VAULT_TOKEN }}" \
          --data '{"lease_id": $lease_id}' \
          ${{ env.VAULT_ADDR }}/v1/sys/leases/revoke
