on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - name: Import Secrets
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: http://mgmt.ndne.co.kr:8200
          token: ${{ secrets.VAULT_TOKEN }}
#           caCertificate: ${{ secrets.VAULT_CA_CERT }}
          secrets: |
            client-kv2/data/dev/dns/13/subdomain aaaa | SAMPLE;
            /aws-terraform-dev/roles/local-execute | AWS_KEYS;
              
      - name: print output
        run: |
          echo ${{ steps.vault.outputs.AWS_KEYS }}
