on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - name: Import Secrets
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.mycompany.com:8200
          token: ${{ secrets.VAULT_TOKEN }}
#           caCertificate: ${{ secrets.VAULT_CA_CERT }}
          secrets: |
              secret/data/ci/aws-terraform-dev accessKey | AWS_ACCESS_KEY_ID ;
              secret/data/ci/aws-terraform-dev secretKey | AWS_SECRET_ACCESS_KEY ;
              secret/data/ci npm_token
              
      - name: print output
        run: |
          echo ${{ steps.vault.outputs.AWS_ACCESS_KEY_ID }}
