on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.mycompany.com:8200
          token: ${{ secrets.VAULT_TOKEN }}
#           caCertificate: ${{ secrets.VAULT_CA_CERT }}
          secrets: |
              secret/data/ci/aws accessKey | AWS_ACCESS_KEY_ID ;
              secret/data/ci/aws secretKey | AWS_SECRET_ACCESS_KEY ;
              secret/data/ci npm_token
      # ...
